### ISSUE TITLE
Build: linux build issues

### ISSUE THREAD

**Issue by AbdelrahmanKhaledd** [alexdovzhanyn/ThetaLang#30] opened 2024-09-26 11:36 UTC
I tried to build the project on Linux, but there were many problems:

- Compiler doesn't change lower-case, upper-case characters in files names, (it changes these characters automatically to fit the right files' names on mac-os) 
```bash
ThetaLang/src/compiler/CodeGen.cpp:17:10: fatal error: lexer/Lexemes.hpp: No such file or directory
   17 | #include "lexer/Lexemes.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
- Compiler doesn't add needed headers, if it wasn't included like `#include<optional>`.
- I think we just need to pass right arguments for compiling to mimic g++ compiler's default options on mac-os.

This [action](https://github.com/AbdelrahmanKhaledd/ThetaLang/actions/runs/11035388133/job/30651244380?pr=1) runs on linux  with the same errors.

**Comment by alexdovzhanyn** [comment] 2024-09-26 15:29
@AbdelrahmanKhaledd Yeah so that lower-case thing has been going on and off for a few weeks. Something in the toolchain is randomly changing the file names and I keep changing them back. Renaming the files to the correct case locally should fix the issue.

It looks like that action you link compiled successfully, but then failed when trying to run the tests. I did a bit of digging into that error you were seeing and it looks like it was caused by some [weird bug](https://github.com/orgs/community/discussions/139743) in Githubs runners, but should be fixed now. I suspect if you run your action again it will work.

Which headers were missing that weren't added by the compiler? Everything should be getting linked by cmake, so if something is missing on Linux that'd be great to know!

**Comment by AbdelrahmanKhaledd** [comment] 2024-09-27 15:04
> that lower-case thing has been going on and off for a few weeks. Something in the toolchain is randomly changing the file names and I keep changing them back. Renaming the files to the correct case locally should fix the issue.

@alexdovzhanyn 
It fixes including files, but there will also be compiling errors:

```make
ThetaLang/src/compiler/CodeGen.cpp:216:22: error: cannot convert ‘std::pair<std::__cxx11::basic_string<char>, int>’ to ‘int’
  216 |             make_pair(assignmentIdentifier, idxOfAssignment)
      |             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      |
      |                      std::pair<std::__cxx11::basic_string<char>, int>

ThetaLang/src/compiler/CodeGen.cpp:245:13: error: ‘assignmentIdentifierPair’ was not declared in this scope
  245 |         if (assignmentIdentifierPair) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~

ThetaLang/src/compiler/CodeGen.cpp:319:52: error: ‘class Theta::SymbolTableStack<std::shared_ptr<Theta::ASTNode> >’ has no member named ‘lookup’
  319 |             shared_ptr<ASTNode> paramValue = scope.lookup(paramName).value();
      |                                                    ^~~~~~
```

> It looks like that action you link compiled successfully, but then failed when trying to run the tests.

it didn't compile successfully, the build has failed, but github actions didn't stop the event and checked it as (a passed event) 
![Screenshot_20240927_173849](https://github.com/user-attachments/assets/be58e884-7f63-45e4-a671-cb5b3c45a85c)

, this's because of the build script file, if any of its commands have failed, it still will return 0 as successful commands, we could fix this.

> Which headers were missing that weren't added by the compiler? 

```make
/ThetaLang/src/compiler/CodeGen.cpp:946:9: error: ‘optional’ was not declared in this scope
  946 |         optional<string> scopeRef = scopeReferences.lookup(identName);
      |         ^~~~~~~~
/ThetaLang/src/compiler/CodeGen.cpp:28:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   27 | #include "cli/cli.cpp"
  +++ |+#include <optional>
   28 | 
```

**Comment by AbdelrahmanKhaledd** [comment] 2024-09-27 16:22
> @AbdelrahmanKhaledd which version of c++ are you using? This project requires c++17 -- it looks like all of the errors you are encountering have to do with std::optional, which was introduced in c++17 and is not available in c++11.

@alexdovzhanyn 
standard version is defined in cmake file as 17, and I have updated build-tools, this [Event with files names changing](https://github.com/AbdelrahmanKhaledd/ThetaLang/actions/runs/11035388133/job/30651244380?pr=1) with same errors and with the correct c++ version

**Comment by alexdovzhanyn** [comment] 2024-09-27 16:33
> @alexdovzhanyn I think, I'm using the correct c++ version, the standard version is defined in cmake file as 17, and I have updated build-tools, this [Event with files names changing](https://github.com/AbdelrahmanKhaledd/ThetaLang/actions/runs/11035388133/job/30651244380?pr=1) with same errors and with the correct c++ version

It looks like that build is still failing with the file name casing issue. I updated master to rename the files manually. Can you give `master` a pull and try again?

**Comment by alexdovzhanyn** [comment] 2024-09-27 17:33
@AbdelrahmanKhaledd I'll play around with it and see if I can get it building with that workflow.

**Comment by AbdelrahmanKhaledd** [comment] 2024-09-28 00:56
I tried to fix these compiler errors, and it works locally with me with these changes [Pr](https://github.com/alexdovzhanyn/ThetaLang/pull/33) but I think it still has a problem with GitHub actions workflow and build fails.

Is there any channel for the project or a group to communicate and discuss things, instead of issue threads?

**Comment by alexdovzhanyn** [comment] 2024-09-28 01:37
Yeah @AbdelrahmanKhaledd I have it almost working on the GitHub actions too in this pr: https://github.com/alexdovzhanyn/ThetaLang/pull/32

If you want, you can hop in this discord channel to discuss: https://discord.gg/mzWgbhGQ6C

I'm driving for the next few hours so I won't be able to respond but we can discuss at some point

**Closed** 2024-09-29 13:48 UTC
Labels: bug
